#!/bin/bash
#
# FILENAME: get_debian_netboot
# AUTHOR:   Bennett Samowich <bennett@foolean.org>
# DATE:     2012-04-19
#
# DESCRIPTION:
#   Download CentOS netboot images.  The script will always download the
#   current active netboot images.  Running this script from cron(1) will
#   ensure that your netboot images are always current, including the new
#   releases as they are made available.
#
#   Note: this script also adds firmware to the image.
#
###############################################################################

# Define some variables
ARCH_LIST="amd64";      # Placeholder for the list of architectures to download
FIRMWARE_LIST="bnx2";   # Placeholder for the list of firmware to download
RELEASE_LIST="";        # Placeholder for the list of releases to download
CUSTOM_RELEASE_LIST=0;  # Flag to denote that we have a custom release list
DEBUG=0;                # Turn on debugging output
ERROR=0;                # Error flag used during argument processing
VERBOSE=0;              # Turn on verbose output
PRUNE=0;                # Prune old releases
OSNAME="debian";        # Operating system name
WGET_VERBOSE="--quiet"; # Placeholder for wget verbosity

# User and group who will own the downloaded image files
USER="tftp"
GROUP="tftp"

# List of image related files to download
IMAGE_FILES="initrd.gz linux"

# Poth to the directory where the netboot files will be stored
PKGDIR="/srv/tftp/packages"

# Root path to download firmware images from
# FIRMWARE_SRC="ftp://ftp.debian.org/debian/pool/non-free/f/firmware-nonfree"

# Logging macro
LOGGER="/usr/bin/logger -it \"$(basename $0)\""

# Get the list of active Debian releases
RELEASE_LIST=$(wget -qO - http://ftp.debian.com/debian/dists/README | \
    grep "\- the released Debian" | awk '{print $3}'                | \
    sort -u | sed -e ':a;N;$!ba;s/\n/ /g')

# debug - helper routine to print debugging messages
debug() {
  if [ "${DEBUG}" -eq 1 ]; then
      echo "debug: $*"
  fi
}

# error - helper routine to print error messages
error() {
    ${LOGGER} "error: $*"
    echo "error: $*"
}

# notice - helper routine to print informational messages
notice() {
  ${LOGGER} "notice: $*"
  if [ "${VERBOSE}" -eq 1 ]; then
    echo "notice: $*"
  fi
}

# usage - how to use this script
usage() {
    echo "Usage: $0 [ OPTIONS ]"
    echo ""
    echo "Where:"
    echo "  -a [ ARCH ]     Architecture to download netboot files for"
    echo "                  (default: ${ARCH_LIST})"
    echo "  -d              Print debugging output (includes -v too)"
    echo "  -f [ FIRMWARE ] List of firmware to include in the netboot image"
    echo "                  (default: ${FIRMWARE_LIST})"
    echo "  -g [ GROUP ]    Group that should own the netboot files"
    echo "                  (default: ${GROUP})"
    echo "  -h              Print this message"
    echo "  -o [ OWNER ]    Username that should own the netboot files"
    echo "                  (default: ${USER})"
    echo "  -p [ DIR ]      Root path to store the netboot files"
    echo "                  (default: ${PKGDIR})"
    echo "  -P              Prune EOL releases"
    echo "  -r [ RELEASE ]  Operating sytem release to download"
    echo "                  (default: ${RELEASE_LIST})"
    echo "  -v              Print more verbose output"
    exit 1
}

# Parse command-line arguments
while getopts "a:dhf:g:r:o:p:Pv" OPTION
do
    case $OPTION in
        a) 
            ARCH_LIST=$(echo $OPTARG | tr '[:upper:]' '[:lower:]');;
        d) 
            DEBUG=1
            VERBOSE=1
            PROGRESS="--progress"
            ;;
        f)
            FIRMWARE_LIST=$(echo $OPTARG | tr '[:upper:]' '[:lower:]');;
        g) 
            GROUP=$OPTARG;;
        o) 
            USER=$OPTARG;;
        p) 
            PKGDIR=${OPTARG};;
        P) 
            PRUNE=1;;
        r) 
            RELEASE_LIST=$(echo $OPTARG | tr '[:upper:]' '[:lower:]')
            CUSTOM_RELEASE_LIST=1
            ;;
        v) 
            VERBOSE=1
            WGET_VERBOSE="--progress=bar"
            ;;
        ?) 
            usage;;
    esac
done

# Make sure we have what we need
if [ "${ARCH_LIST}" == "" ]; then
    error "Must specify an architecture type (-a)"
    ERROR=1
fi
if [ "${RELEASE_LIST}" == "" ]; then
    error "Must specify a release (-r)"
    ERROR=1
fi
if [ ${ERROR} -eq 1 ]; then
    usage
    exit 1;     # Should never get here
fi

# Debugging output
debug "ARCH_LIST     = ${ARCH_LIST}" 
debug "FIRMWARE_LIST = ${FIRMWARE_LIST}"
debug "RELEASE_LIST  = ${RELEASE_LIST}"
debug "USER          = ${USER}"
debug "GROUP         = ${GROUP}"
debug "PATH          = ${PKGDIR}"

# Ensure our package directory exists
mkdir -p "${PKGDIR}"
chmod -R u-wx,u+rwX,go-rwx "${PKGDIR}"


# Release loop: Iterate over the list of releases
for RELEASE in ${RELEASE_LIST}
do
    debug "Getting netboot images for ${RELEASE}"

    # Source path to the firmware
    FIRMWARE_SRC="http://cdimage.debian.org/cdimage/unofficial/non-free/firmware/${RELEASE}/current/firmware.tar.gz"

    # Destination path for the firmware
    FIRMWARE_DIR="${PKGDIR}/${OSNAME}/${RELEASE}/firmware"

    # Download the firmware for this release only if we're going to use it
    if [ "${FIRMWARE_LIST}" != "" ]
    then
        debug "Getting firmware file for ${RELEASE}"

        # Create the destination directory for the firmware
        debug "Creating '${FIRMWARE_DIR}'"
        mkdir -p "${FIRMWARE_DIR}"
    
        # Download the firmware
        notice "Downloading '${FIRMWARE_SRC}'"
        wget "${WGET_VERBOSE}"                                           \
            -O "${PKGDIR}/${OSNAME}/${RELEASE}/firmware/firmware.tar.gz" \
            "${FIRMWARE_SRC}"
    
        # Unpack the firmware
        if [ -f "${PKGDIR}/${OSNAME}/${RELEASE}/firmware/firmware.tar.gz" ]
        then
            debug "Unpacking '${FIRMWARE_DIR}/firmware.tar.gz'"
            tar xf "${FIRMWARE_DIR}/firmware.tar.gz" -C "${FIRMWARE_DIR}"
        else
            error "Unable to download firmware file, quitting"
            exit 1;
        fi
    fi

    # Architecture loop: Iterate over the list of architectures
    for ARCH in ${ARCH_LIST}
    do
        # Download the image files for this release and architecture
        debug "Getting netboot images for ${RELEASE} ${ARCH}"

        # Source path to the netboot images
        IMAGE_SRC="http://ftp.debian.org/debian/dists/${RELEASE}/main/installer-${ARCH}/current/images/netboot/debian-installer/${ARCH}"

        # Destination path for the release images
        RELEASE_DIR="${PKGDIR}/${OSNAME}/${RELEASE}/${ARCH}"

        # Create the destination directory for the release image
        debug "Creating '${RELEASE_DIR}'"
        mkdir -p "${RELEASE_DIR}"

        # Image loop: Iterate over the list of image files
        for IMAGE_FILE in ${IMAGE_FILES}
        do
            debug "Dowloading ${IMAGE_FILE} for ${RELEASE} ${ARCH}"
        
            # Download the image file
            notice "Downloading '${IMAGE_SRC}/${IMAGE_FILE}'"
            wget "${WGET_VERBOSE}"  \
                -O "${RELEASE_DIR}/${IMAGE_FILE}" "${IMAGE_SRC}/${IMAGE_FILE}"
       
            # Process the firmware list creating initrd+firmware.gz
            if [ "${IMAGE_FILE}" == "initrd.gz" ]; then
                if [ "${FIRMWARE_LIST}" != "" ]; then
                    debug "Adding firmware to initrd.gz"
        
                    # Working directory for adding firmware into the image
                    RELEASE_TEMP_DIR="${RELEASE_DIR}/temp"
        
                    # Create the firmware working directory for this release
                    debug "Creating '${RELEASE_TEMP_DIR}'"
                    mkdir "${RELEASE_TEMP_DIR}"
        
                    # Change into the firmware working directory
                    cd "${RELEASE_TEMP_DIR}"
        
                    # Unpack the image file
                    debug "Unpacking ${RELEASE_DIR}/initrd.gz"
                    zcat ../initrd.gz | cpio -i
        
                    # Iterate over the list of firmware adding them to the image
                    for FIRMWARE in ${FIRMWARE_LIST}
                    do
                        notice "Adding firmware '${FIRMWARE}' to ${RELEASE} ${ARCH} image"
        
                        # Get the full path to the firmware we're adding
                        FIRMWARE_FILE=$(find "${FIRMWARE_DIR}" -type f \
                            -name "firmware-${FIRMWARE}_*_all.deb")

                        # Insert the firmware if we found it
                        if [ "${FIRMWARE_FILE}" != "" ]; then
                            dpkg-deb -x "${FIRMWARE_FILE}" .
                        fi
                    done;   # Firmware loop
        
                    # Compress the resulting image into initrd+firmware.gz
                    notice "Compress image as ${RELEASE_DIR}/initrd+firmware.gz"
                    find . -print0 | cpio -0 -H newc -o | \
                        gzip -c > ../initrd+firmware.gz

                    # Clean up the temporary working directory
                    debug "Cleaning up '${RELEASE_TEMP_DIR}'"
                    cd "${RELEASE_DIR}"
                    rm -rf temp
                fi
            fi
        done;   # Image loop
    done;   # Architecture loop

    # Clean up firmware directory
    if [ -d "${FIRMWARE_DIR}" ]; then
        debug "Cleaning up '${FIRMWARE_DIR}'"
        rm -rf "${FIRMWARE_DIR}"
    fi
done;   # Release loop

# Set owner and permissions on the directories and files
chown -R ${USER}:${GROUP}   "${PKGDIR}/${OSNAME}"
chmod -R go-rwx             "${PKGDIR}/${OSNAME}"
chmod -R u+rwX              "${PKGDIR}/${OSNAME}"

# Prune directories not part of the current release list
if [ ${CUSTOM_RELEASE_LIST} -eq 0 ] && [ ${PRUNE} -eq 1 ]; then
    EOL_RELEASES=$(find "${PKGDIR}/${OSNAME}/"* -type d -prune \
                    -exec basename {} \; | sort -u | \
                    sed -e ':a;N;$!ba;s/\n/ /g')

    # Debian uses release names so we need to traverse the
    # active release list and remove them from the list of
    # directories to be pruned
    for RELEASE in ${RELEASE_LIST}
    do
        EOL_RELEASES=$(echo "${EOL_RELEASES}" | sed -e "s/${RELEASE}//")
    done

    debug "EOL_RELEASES = '${EOL_RELEASES}'"

    for EOL_RELEASE in ${EOL_RELEASES}
    do 
        notice "Cleaning up EOL/EOS release '${EOL_RELEASE}'"
        rm -rf "${PKGDIR}/${OSNAME}/${EOL_RELEASE}"
    done
fi
