#!/bin/bash
#
# FILENAME: get_openbsd_netboot
# AUTHOR:   Bennett Samowich <bennett@foolean.org>
# DATE:     2012-04-19
#
# DESCRIPTION:
#   Download OpenBSD netboot images.  The script will always download the
#   current active netboot images.  Running this script from cron(1) will
#   ensure that your netboot images are always current, including the new
#   releases as they are made available.
#
#   This script will also create a 'etc' directory within directory of each
#   release.  A 'boot.conf' and 'random.seed' file will be created inside
#   the 'etc' directory.  Activating a specific version will be a matter of
#   symlinking the release's etc directory to the root of the tftp tree.
#
################################################################################

# Define some variables
ARCH_LIST="amd64";      # Placeholder for the list of architectures to download
FIRMWARE_LIST="";       # Placeholder for the list of firmware to download
RELEASE_LIST="";        # Placeholder for the list of releases to download
CUSTOM_RELEASE_LIST=0;  # Flag to denote that we have a custom release list
DEBUG=0;                # Turn on debugging output
ERROR=0;                # Error flag used during argument processing
VERBOSE=0;              # Turn on verbose output
PRUNE=0;                # Prune old releases
OSNAME="openbsd";       # Operating system name
WGET_VERBOSE="--quiet"; # Placeholder for wget verbosity

# User and group who will own the downloaded image files
USER="tftp"
GROUP="tftp"

# List of image related files to download
IMAGE_FILES="pxeboot bsd.rd"

# Poth to the directory where the netboot files will be stored
PKGDIR="/srv/tftp/packages"

# Logging macro
LOGGER="/usr/bin/logger -it \"$(basename $0)\""

# Get the list of active OpenBSD releases
RELEASE_LIST=$(wget -qO - http://ftp.openbsd.org/pub/OpenBSD | \
    grep "folder" | sed -e 's/^.*">//' -e 's/\/<.*//'        | \
    grep "^[0-9]" | sort -u | sed -e ':a;N;$!ba;s/\n/ /g')

# debug - helper routine to print debugging messages
debug() {
  if [ "${DEBUG}" -eq 1 ]; then
      echo "debug: $*"
  fi
}

# error - helper routine to print error messages
error() {
    ${LOGGER} "error: $*"
    echo "error: $*"
}

# notice - helper routine to print informational messages
notice() {
  ${LOGGER} "notice: $*"
  if [ "${VERBOSE}" -eq 1 ]; then
    echo "notice: $*"
  fi
}

# usage - how to use this script
usage() {
    echo "Usage: $0 [ OPTIONS ]"
    echo ""
    echo "Where:"
    echo "  -a [ ARCH ]     Architecture to download netboot files for"
    echo "                  (default: ${ARCH_LIST})"
    echo "  -d              Print debugging output (includes -v too)"
    echo "  -g [ GROUP ]    Group that should own the netboot files"
    echo "                  (default: ${GROUP})"
    echo "  -h              Print this message"
    echo "  -o [ OWNER ]    Username that should own the netboot files"
    echo "                  (default: ${USER})"
    echo "  -p [ DIR ]      Root path to store the netboot files"
    echo "                  (default: ${PKGDIR})"
    echo "  -r [ RELEASE ]  Operating sytem release to download"
    echo "                  (default: ${RELEASE_LIST})"
    echo "  -v              Print more verbose output"
    exit 1
}

# Parse command-line arguments
while getopts "a:dhg:r:o:p:Pv" OPTION
do
    case $OPTION in
        a) 
            ARCH_LIST=$(echo $OPTARG | tr '[:upper:]' '[:lower:]');;
        d) 
            DEBUG=1
            VERBOSE=1
            PROGRESS="--progress"
            ;;
        g) 
            GROUP=$OPTARG;;
        o) 
            USER=$OPTARG;;
        p) 
            PKGDIR=${OPTARG};;
        P) 
            PRUNE=1;;
        r) 
            RELEASE_LIST=$(echo $OPTARG | tr '[:upper:]' '[:lower:]')
            CUSTOM_RELEASE_LIST=1
            ;;
        v) 
            VERBOSE=1
            WGET_VERBOSE="--progress=bar"
            ;;
        ?) 
            usage;;
    esac
done

# Make sure we have what we need
if [ "${ARCH_LIST}" == "" ]; then
    error "Must specify an architecture type (-a)"
    ERROR=1
fi
if [ "${RELEASE_LIST}" == "" ]; then
    error "Must specify a release (-r)"
    ERROR=1
fi
if [ ${ERROR} -eq 1 ]; then
    usage
    exit 1;     # Should never get here
fi

# Debugging output
debug "ARCH_LIST     = ${ARCH_LIST}" 
debug "RELEASE_LIST  = ${RELEASE_LIST}"
debug "USER          = ${USER}"
debug "GROUP         = ${GROUP}"
debug "PATH          = ${PKGDIR}"

# Ensure our package directory exists
mkdir -p "${PKGDIR}"
chmod -R u-w,u+rX,go-rwx "${PKGDIR}"

# Release loop: Iterate over the list of releases
for RELEASE in ${RELEASE_LIST}
do
    debug "Getting netboot images for ${RELEASE}"

    # Architecture loop: Iterate over the list of architectures
    for ARCH in ${ARCH_LIST}
    do
        # Download the image files for this release and architecture
        debug "Getting netboot images for ${RELEASE} ${ARCH}"

        # Source path to the netboot images
        IMAGE_SRC="http://ftp.openbsd.org/pub/OpenBSD/${RELEASE}/${ARCH}"

        # Destination path for the release images
        RELEASE_DIR="${PKGDIR}/${OSNAME}/${RELEASE}/${ARCH}"

        # Create the destination directory for the release image
        debug "Creating '${RELEASE_DIR}'"
        mkdir -p "${RELEASE_DIR}"

        # Image loop: Iterate over the list of image files
        for IMAGE_FILE in ${IMAGE_FILES}
        do
            debug "Dowloading ${IMAGE_FILE} for ${RELEASE} ${ARCH}"
        
            # Download the image file
            notice "Downloading '${IMAGE_SRC}/${IMAGE_FILE}'"
            wget "${WGET_VERBOSE}" \
                -O "${RELEASE_DIR}/${IMAGE_FILE}" "${IMAGE_SRC}/${IMAGE_FILE}"

            if [ "${IMAGE_FILE}" == "pxeboot" ]
            then
                mv "${RELEASE_DIR}/${IMAGE_FILE}" \
                   "${RELEASE_DIR}/${IMAGE_FILE}.0"
            fi
        done;   # Image loop

        # Create the /etc directory
        notice "Creating /etc directory for ${RELEASE} ${ARCH}"
        if [ ! -d "${RELEASE_DIR}/etc" ]
        then
            mkdir "${RELEASE_DIR}/etc"
        fi

        # Create the boot.conf file
        notice "Creating boot.conf for ${RELEASE} ${ARCH}"
        echo "set image packages/openbsd/${RELEASE}/amd64/bsd.rd" \
            > "${RELEASE_DIR}/etc/boot.conf"

        # Create the random.seed file
        notice "Creating random.seed for ${RELEASE} ${ARCH}"
        dd if=/dev/random of="${RELEASE_DIR}/etc/random.seed" \
           bs=512 count=1 status=noxfer

    done;   # Architecture loop
done;   # Release loop

# Set owner and permissions on the directories and files
chown -R ${USER}:${GROUP}   "${PKGDIR}/${OSNAME}"
chmod -R go-rwx             "${PKGDIR}/${OSNAME}"
chmod -R u+rwX              "${PKGDIR}/${OSNAME}"

# Prune directories not part of the current release list
if [ ${CUSTOM_RELEASE_LIST} -eq 0 ] && [ ${PRUNE} -eq 1 ]; then
    EOL_RELEASES=$(find "${PKGDIR}/${OSNAME}/"* -type d -prune \
                    -exec basename {} \; | sort -u | \
                    sed -e ':a;N;$!ba;s/\n/ /g')

    for RELEASE in ${RELEASE_LIST}
    do
        EOL_RELEASES=$(echo "${EOL_RELEASES}" | sed -e "s/${RELEASE}//")
    done

    debug "EOL_RELEASES = '${EOL_RELEASES}'"

    for EOL_RELEASE in ${EOL_RELEASES}
    do 
        notice "Cleaning up EOL/EOS release '${EOL_RELEASE}'"
        rm -rf "${PKGDIR}/${OSNAME}/${EOL_RELEASE}"
    done
fi
